### ISSUE TITLE
I can include this library in my project

### ISSUE THREAD

**Issue by IP696** [SpecialCyCi/AndroidResideMenu#53]
I can include this library in my project
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\Users\zen_75\AppData\Local\Android\sdk\build-tools\22.0.1\dx.bat --dex --no-optimize --output C:\projects\android-customer\app\build\intermediates\dex\debug --input-list=C:\projects\android-customer\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

**Comment by polok** [comment]
This is a limitation of Dalvik machine. Here https://developer.android.com/tools/building/multidex.html you will find what you have to add into your build.gradle and Application class to bring it to work.
